// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful API Response",
            "schema": {
              "$ref": "#/definitions/IProducts"
            }
          },
          "404": {
            "description": "Products not found",
            "schema": {
              "$ref": "#/definitions/ICustomErr"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful API Response",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/ICustomErr"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "IStock": {
      "properties": {
        "count": {
          "title": "IStock.count",
          "type": "number"
        },
        "product_id": {
          "title": "IStock.product_id",
          "type": "string"
        }
      },
      "required": [
        "count",
        "product_id"
      ],
      "additionalProperties": false,
      "title": "IStock",
      "type": "object"
    },
    "IProduct": {
      "properties": {
        "count": {
          "title": "IProduct.count",
          "type": "number"
        },
        "description": {
          "title": "IProduct.description",
          "type": "string"
        },
        "id": {
          "title": "IProduct.id",
          "type": "string"
        },
        "price": {
          "title": "IProduct.price",
          "type": "number"
        },
        "title": {
          "title": "IProduct.title",
          "type": "string"
        }
      },
      "required": [
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "IProduct",
      "type": "object"
    },
    "IProducts": {
      "items": {
        "$ref": "#/definitions/IProduct",
        "title": "IProducts.[]"
      },
      "title": "IProducts.[]",
      "type": "array"
    },
    "ICustomErr": {
      "properties": {
        "message": {
          "title": "ICustomErr.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "ICustomErr",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};